{"type": "company", "name": "RTi Research", "url": "https://rtiresearch.com/", "wikipedia": "https://en.wikipedia.org/wiki/RTI_International", "wikidata": null, "linkedin": null, "attributes": {"Trade name": "RTI International", "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Hypothesis", "url": "https://www.hypothesisgroup.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Bellomy Research", "url": "https://www.bellomy.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "KS&R", "url": "https://ksrinc.com/", "wikipedia": "https://en.wikipedia.org/wiki/KS%26R", "wikidata": null, "linkedin": null, "attributes": {"Trade name": "Knowledge Systems and Research, Inc.", "Founded": 1983, "Number of employees": 209}}
{"type": "company", "name": "NAXION", "url": "https://www.naxionthinking.com/", "wikipedia": "https://en.wikipedia.org/wiki/National_Analysts", "wikidata": null, "linkedin": null, "attributes": {"Trade name": "NAXION", "Founded": 1911, "Number of employees": null}}
{"type": "company", "name": "InSites Consulting", "url": "http://www.insites-consulting.com", "wikipedia": null, "wikidata": null, "linkedin": "https://www.linkedin.com/company/insites-consulting/about/", "attributes": {"Trade name": "InSites Consulting", "Founded": 1997, "Number of employees": 570}}
{"type": "company", "name": "Maru/Matchbox", "url": "https://www.marugroup.net/maru-matchbox", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Chadwick Martin Bailey (CMB)", "url": "https://www.cmbinfo.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Screen Engine/ASI", "url": "https://www.screenengineasi.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "MarketVision Research", "url": "https://mv-research.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "The Link Group", "url": "https://www.tlg.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "SSRS", "url": "https://ssrs.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "BVA Group", "url": "https://www.bva-group.com/en/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "radius | illumination", "url": "https://radiusinsights.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Market Force", "url": "https://www.marketforce.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "SMG", "url": "https://www.smg.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Hanover Research", "url": "https://www.hanoverresearch.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Directions Research", "url": "https://directionsresearch.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Fors Marsh Group (FMG)", "url": "https://www.forsmarshgroup.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "National Research Group (NRG)", "url": "https://www.nationalresearchgroup.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Cello Health", "url": "https://cellohealth.com/us/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Macromill Group", "url": "https://group.macromill.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "C Space", "url": "https://cspace.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Burke", "url": "https://burke.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "YouGov", "url": "https://today.yougov.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Phoenix Marketing International", "url": "https://www.phoenixmi.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Concentrix", "url": "https://www.concentrix.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Escalent", "url": "https://escalent.co/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "dunnhumby", "url": "https://www.dunnhumby.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "NRC Health", "url": "https://nrchealth.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Clarivate", "url": "https://clarivate.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Wood Mackenzie", "url": "https://www.woodmac.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Material", "url": "https://www.materialplus.io/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "ICF", "url": "https://www.icf.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "J.D. Power", "url": "https://www.jdpower.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Forrester Research Services", "url": "https://go.forrester.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "GfK", "url": "https://www.gfk.com/home", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "comScore", "url": "https://www.comscore.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "The NPD Group", "url": "https://www.npd.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Westat", "url": "https://www.westat.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Information Resources Incorporated (IRI)", "url": "https://www.iriworldwide.com/en-us", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Kantar", "url": "https://www.kantar.com/north-america", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Gartner Research", "url": "https://www.gartner.com/en", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "IQVIA", "url": "https://www.iqvia.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": null, "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Nielsen", "url": "https://global.nielsen.com/global/en/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": "The Nielsen Company", "Founded": 1923, "Number of employees": 43000}}
{"type": "company", "name": "Accenture", "url": "https://www.accenture.com", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": "Accenture plc", "Founded": 1989, "Number of employees": 699000}}
{"type": "company", "name": "Kraft Foods", "url": "https://kraftheinzcompany.com", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": "Kraft Foods Group, Inc.", "Founded": 2012, "Number of employees": 22500}}
{"type": "company", "name": "Comcast", "url": "https://corporate.comcast.com", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": "Comcast Corporation", "Founded": 2012, "Number of employees": 190000}}
{"type": "company", "name": "SAS Institute", "url": "https://www.sas.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": "SAS Institute Inc.", "Founded": null, "Number of employees": 13939}}
{"type": "company", "name": "AWS", "url": "https://aws.amazon.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": "Amazon Web Services, Inc.", "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Google", "url": "https://www.google.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": "Google LLC", "Founded": 1998, "Number of employees": 139995}}
{"type": "company", "name": "SIS International Research", "url": "https://www.sisinternational.com/", "wikipedia": null, "wikidata": "Q7390490", "linkedin": null, "attributes": {"Trade name": "SIS International Research", "Founded": 1984, "Number of employees": null}}
{"type": "company", "name": "Cascade Insights", "url": "https://www.cascadeinsights.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": "Cascade Insights", "Founded": null, "Number of employees": null}}
 {"type": "company", "name": "Ascendant Consulting Firm", "url": "https://ascendantconsultingfirm.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": "Ascendant Consulting Firm", "Founded": null, "Number of employees": null}}
{"type": "company", "name": "Proactive Worldwide", "url": "https://www.proactiveworldwide.com/", "wikipedia": null, "wikidata": null, "linkedin": null, "attributes": {"Trade name": "Proactive Worldwide, Inc.", "Founded": 1995, "Number of employees": null}}