{"type": "Article", "name": "AMA 2020 Top 50", "url": "https://www.ama.org/marketing-news/2020-top-50/", "text": "This AMA page includes anchor tags with URLs to the home pages of the top companies. These can be obtained by using Google Chrome DevTools to obtain the source code for the page and then manually searching the page for the desired anchor tags and company URLs."}
{"type": "Article", "name": "AMA 2017 Top 50", "url": "https://web.archive.org/web/20171116034342/https://www.ama.org/publications/MarketingNews/Pages/the-ama-gold-report-2017-top-50-market-research-firms.aspx?sq=honomichl", "text": "This AMA page includes extensive analysis of marketing research professional services."}
{"type": "Industry", "name": "Marketing Research", "attributes": {"NAICScode": 541910, "NAICStitle": "Marketing Research and Public Opinion Polling", "description": "Industry category studied extensively by the American Marketing Association (AMA) and the American Association for Public Opinion Research (AAPOR). Related industry categories include NAICS code 541613 Marketing Consulting Services and NAICS code 541720 Research and Development in the Social Sciences and Humanities."}}
{"type": "Industry", "name": "Computer Systems Design Services", "attributes": {"NAICScode": 541512, "NAICStitle": "Computer Systems Design Services", "description": null}}
{"type": "Industry", "name": "Food Manufacturing", "attributes": {"NAICScode": 311999, "NAICStitle": "All Other Miscellaneous Food Manufacturing", "description": null}}
{"type": "Industry", "name": "Telecommunications Resellers", "attributes": {"NAICScode": 517911, "NAICStitle": "Telecommunications Resellers", "description": null}}
{"type": "Product", "name": "Nielsen Audience Measurement", "description": "Know everything about your audiences with cross-platform measurement data comprised of the entire population and its shifting habits."}
{"type": "Product", "name": "Nielsen Media Planning", "description": "Power your media planning and invest where it matters most with comprehensive data that shows where, when, and how to reach your target audiences."}
{"type": "Product", "name": "Nielsen Marketing Optimization", "description": "Maximize ROI by understanding how your marketing and advertising reaches and impacts audiences throughout the customer journey."}
{"type": "Product", "name": "Nielsen Content Metadata", "description": "Discover what audiences want and connect them to more of the media, music, sports, and video content they love."}
{"type": "Product", "name": "Google Trends", "description": "Explore what the world is searching."}
{"type": "Industry", "name": "Information Services", "attributes": {"NAICScode": 519190, "NAICStitle": "All Other Information Services", "description": null}}
{"type": "Product", "name": "YouGov Audience Intelligence", "description": "Equip yourself with the knowledge to deliver more successful campaigns. With over 20 million registered panel members worldwide, YouGov's Living Consumer Intelligence helps you build the most complete picture of your customers' complex lives. Our market-leading audience intelligence platform has over one million unique data points to choose from in 49 markets and it's growing every day."}
{"type": "Group", "name": "Data Scientists", "description": "White-collar workers who understand measurement, research design, traditional statistics, and machine learning methods."}
{"type": "Person", "name": "Tom Miller", "attributes": {"affiliation":["Northwestern University", "Research Publishers LLC"]}}
{"type": "Review", "name": "Tom Miller Review of Nielsen", "table": "review_person_company"}
{"type": "Article", "name": "Nielsen Corporate Profile", "table": "article_company_information"}
{"type": "Article", "name": "Nielsen Holdings", "table": "article_company_information"}
{"type": "Article", "name": "2020 Top 50 U.S. Market Research and Data Analytics Companies", "table": "article_industry_information"}
{"type": "Article", "name": "Identifying Trends From the 2020 U.S. Top 50 Report", "table": "article_industry_information"}
{"type": "Data", "name": "Company Revenue (millions of dollars)", "table": "data_company_revenue_millions"}
{"type": "Data", "name": "Key Sources of Competitive Intelligence", "table": "data_key_sources_competitive_intelligence"}
{"type": "Article", "name": "About SIS International Research", "table": "article_company_information"}
{"type": "Article", "name": "About Cascade Insignts", "table": "article_company_information"}
{"type": "Article", "name": "About Ascendant Consulting Firm", "table": "article_company_information"}
{"type": "Article", "name": "About Proactive Worldwide", "table": "article_company_information"}
{"type": "Article", "name": "National Analysts", "table": "article_company_information"}
{"type": "Article", "name": "InSites Consulting", "table": "article_company_information"}
{"type": "Industry", "name": "Marketing Consulting", "attributes": {"NAICScode": 541613, "NAICStitle": "Marketing Consulting Services", "description": "This U.S. industry comprises establishments primarily engaged in providing operating advice and assistance to businesses and other organizations on marketing issues, such as developing marketing objectives and policies, sales forecasting, new product developing and pricing, licensing and franchise planning, and marketing planning and strategy."}}
{"type": "Industry", "name": "Management Consulting", "attributes": {"NAICScode": 541611, "NAICStitle": "Administrative Management and General Management Consulting Services", "description": "This U.S. industry comprises establishments primarily engaged in providing operating advice and assistance to businesses and other organizations on administrative management issues, such as financial planning and budgeting, equity and asset management, records management, office planning, strategic and organizational planning, site selection, new business start-up, and business process improvement. This industry also includes establishments of general management consultants that provide a full range of administrative, human resource, marketing, process, physical distribution, logistics, or other management consulting services to clients."}}